# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af342cdcaeaa38bd164ab97595abf70ae66a3e74c8e460b96c2cb8a0badb98edddc03a002086d457384bcf544648c0d06bcfac0364f20b1375f76ef0e14f7c37

test:
  secret_key_base: 2dc4483c051ed3cd7f6fb2e5325c4b7b15fd13221efb1c61f05be11da32fbc0cebdfc3dcd4f1e5472762f6cc3f2a661b68daa3061e1e586e8a49b095997a5df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
